#
# Talismans
# by Auxilor
#

crafting:
  discover: true # If players should automatically have recipes added to their crafting table.

read-enderchest: true # If a player's ender chest should be checked for talismans
read-shulkerboxes: true # If a player's shulker boxes should be checked for talismans
top-level-only: true # If only the top level of any given talisman should be activated

offhand-only: false # If talismans or shulkers of talismans need to be in the offhand to work

cannot-afford:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

use-faster-move-trigger: true # Disable if you want move trigger to detect sub-1-block movements
raytrace-distance: 80 # The distance that alt_click should check for a location