#
# Talismans
# by Auxilor
#

crafting:
  discover: true # If players should automatically have recipes added to their crafting table.

read-enderchest: true # If a player's ender chest should be checked for talismans
read-shulkerboxes: true # If a player's shulker boxes should be checked for talismans
top-level-only: true # If only the top level of any given talisman should be activated

offhand-only: false # If talismans or shulkers of talismans need to be in the offhand to work

bag:
  title: "Talisman Bag"
  rows: 4
  blocked-item: black_stained_glass_pane name:"&cYour talisman bag is not big enough!"

cannot-afford:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cannot-afford-type:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

point-names: # If you have point names that look ugly (eg g_souls) then you can map them to nice names to be shown to players.
  example_point: "Nicely Formatted Point"

use-faster-move-trigger: true # Disable if you want move trigger to detect sub-1-block movements
raytrace-distance: 80 # The distance that alt_click should check for a location
block-item-drop-place-check: true # If the block_item_drop trigger should only fire on naturally placed blocks (prevents dupes)

potions:
  icon:
    permanent: true
    triggered: true
  ambient:
    permanent: false
    triggered: true
  particles:
    permanent: false
    triggered: true