#
# Talismans
# by Auxilor
#

description:
  # How many characters to have on each line of description.
  wrap: 20

strengths:
  talisman:
    color: "&e"
    shine: false
  ring:
    color: "&c"
    shine: false
  relic:
    color: "&d"
    shine: true

drops:
  ### ADVANCED OPTIONS
  collate: false
  # Instead of directly dropping all drops and xp, some intensive talismans will push to a collated queue.
  # At the end of each tick, the queue will be pushed rather than pushing on every drop creation
  # This will massively improve mining performance on servers, however it is experimental and may not function correctly.