name: Talismans
version: ${projectVersion}
main: com.willfp.talismans.TalismansPlugin
api-version: 1.15
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - mcMMO

commands:
  talreload:
    description: Reloads config
    permission: talismans.reload
  taldebug:
    description: Debug information
    permission: talismans.taldebug
  talismans:
    description: Shows talisman inventory
    permission: talismans.inventory

permissions:
  talismans.*:
    description: All talismans permissions
    default: op
    children:
      talismans.reload: true
      talismans.taldebug: true
      talismans.talismans: true
      talismans.fromtable.*: true

  talismans.reload:
    description: Allows reloading the config
    default: op
  talismans.taldebug:
    description: Allows the use of /taldebug to print verbose debug information to console
    default: op
  talismans.inventory:
    description: Allows the use of /talismans to show the player's talisman inventory.
    default: true
  talismans.fromtable.*:
    description: Allows crafting all talismans
    default: true