name: Talismans
version: ${projectVersion}
main: com.willfp.talismans.TalismansPlugin
api-version: 1.16
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - mcMMO

commands:
  talreload:
    description: Reloads config
    permission: talismans.reload
  talgive:
    description: Give a player a talisman
    permission: talismans.give

permissions:
  talismans.*:
    description: All talismans permissions
    default: op
    children:
      talismans.reload: true
      talismans.give: true
      talismans.fromtable.*: true

  talismans.reload:
    description: Allows reloading the config
    default: op
  talismans.give:
    description: Allows the use of /talgive.
    default: op
  talismans.fromtable.*:
    description: Allows crafting all talismans
    default: true